name: bendable_slider
description: "A customizable curved slider for your Flutter app."
version: 0.0.1
homepage: https://github.com/akashelaunchinfotech/BendableSlider/tree/master/blendable_slider

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: